# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8159d5057dcdce399792120a3368d36d1d8863215676bed801b68345eb06e18f65cd8f1f63869c0b1232c37f5711577b6ac4a6e47732ee34712595acd76fcd4f

test:
  secret_key_base: 93426c34e6db161fee973c919ba79829a41a94e97b0f1f7d687760c56c174e0f64f846c9691b3dddd0dfbb7c0afc3d9e46c9526fc4b881f514e94ff008566095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
